### ISSUE TITLE
Feature: User can view Currency Table

### ISSUE THREAD

**Issue by K-Karneboge** [K-Karneboge/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
On load a table is generated with all trades of the current snapshot of [poe.ninja](https://github.com/5k-mirrors/misc-poe-tools/blob/master/doc/poe-ninja-api.md) market data. 

## 📐 Functionality
User will see a fixed header scrollable table showing the buy and sell price of currency items along with calculated ROI.
> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/20393497/192832177-29ef9aca-8070-47c2-93c6-38c5586fb408.png)
![image](https://user-images.githubusercontent.com/20393497/192832339-e32cb2d5-9ac4-477a-8118-21ffb566eb12.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] add a `div[data-view="currency"]` to the HTML
- [ ] add table to the `div[data-view="currency"]` 
   - [ ] Fixed Table Head with scrollable body
- [ ] ensure that the table looks nice on both mobile-sized and desktop-sized screens.
- [ ] create a data model array
- [ ] Listen for `'load'`  event to append matching currency type data to objects created within the data model array
- [ ] create a function that calculates ROI
   - [ ] make sure the function has exit function for missing buy / sell data and generates 'null'
   - [ ] make the function round to the nearest first decimal percentage % (IE: 5.2%, 10.6%, -5.2, -190.5%)
- [ ] create a function that appends tr to the dom with - name, icon,  buy/ sell and ROI
   - [ ] insufficient data generates a N/A within the field. 
   - [ ] passthrough function adds/changes a class for positive; negative ROI (for css styling) 

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
