### ISSUE TITLE
Feature: User can search table by Name

### ISSUE THREAD

**Issue by K-Karneboge** [K-Karneboge/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
Name search bar. 

## 📐 Functionality
User is able to filter item names out in the search bar. 
> ##### A description of how the application will work from the perspective of the user.

-[ ] Create function that applies class to tr that dont include the string in the search bar to hide elements. 
-[ ] Create listener event for user entry.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/20393497/192866052-03c11b8a-78a4-4331-8f87-96ae40221987.png)

![image](https://user-images.githubusercontent.com/20393497/192866184-f4dd4ac0-939a-4d83-9de3-3fa901d6c68e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] 
- [ ] ... 

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
