### ISSUE TITLE
Feature: User can generate a trade listing.

### ISSUE THREAD

**Issue by K-Karneboge** [K-Karneboge/ajax-project#3]
## ⚙️ Feature
User can generate a trade index text.
> ##### What capability will users have when this feature is merged?
When selecting from the table. The user can generate the text string to clipboard of the appropriate value. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When the user selects the name field within a table it will open a modal which gives them options to create buy or sell orders. The buttons add the string of the trade order to their clipboard for use in the client. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/20393497/192870662-d35e1a1b-fde8-4465-9397-d43456019792.png)
![image](https://user-images.githubusercontent.com/20393497/192871279-0fa11196-540d-4897-b71c-26f438cb0fa0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] Create modal for holding the buttons. 4 buttons and a title ; 2 buttons for creating buy and sell 1 for close and one as a placeholder for "My Trades"
- [ ] make sure the modal looks good in both mobile and desktop versions
- [ ] add callback function that adds listening events to open the modal to the DOM when creating table. 
- [ ] create function that translates the price into a listing. " ~price [value] [currency name in client]"
- [ ] apply event listeners to the buttons for buy and sell that take the correct values of the table in.
- [ ] make button unselectable for table entries with invalid values. 
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
