### ISSUE TITLE
Feature: User can sort set minimum ROI

### ISSUE THREAD

**Issue by K-Karneboge** [K-Karneboge/ajax-project#4]
## ⚙️ Feature
User can set a minimum ROI for the table. 
> ##### What capability will users have when this feature is merged?

## 📐 Functionality
User has the option to input a field that sets a minimum ROI to be displayed, if empty the table will display all ROI that fit the current criteria. 
> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/20393497/192885458-c287ead1-6941-4282-a5f7-7a26e25d7dc4.png)
![image](https://user-images.githubusercontent.com/20393497/192885567-a6e2397c-7a57-432f-a11d-e580d87289fc.png)

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] Create form element and style. make sure that its spaced properly in mobile/desktop
- [ ]  Disallow non number and special  characters from input form. 
- [ ] Create event listener function that styles the form entry box on user entry.
- [ ] Make function that compares the ROI in tables and applies hidden class to those that don't match criteria. Always assumes null or n/a doesn't match criteria.
- [ ] apply event listener to form  on user entry looking for valid entry. Number.parseFloat()
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
