### ISSUE TITLE
Feature: User can add or remove their trades from their table. 

### ISSUE THREAD

**Issue by K-Karneboge** [K-Karneboge/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can add or remove their trades from table
## 📐 Functionality
User has a table that is made of saved entries that can be viewed from their trades view
> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/20393497/192890888-2743a7f1-eedd-4304-9b6d-decd5c913d95.png)
![image](https://user-images.githubusercontent.com/20393497/192891028-82663ffa-621e-4f2a-9a6a-df2e1713f860.png)

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create an array for storing user data
- [ ] Create the function that handles the 'my trades' objects.
    - [ ] Create a function creates an object from the data in the tr and appends it to the data array in a way passable through the table creation function if that object isnt already in the array. 
    - [ ] Create a second function that removes an object from the user data array if passed matching data.
    - [ ] Use both functions as callbacks in the handling function. 
- [ ] Add modal on click of the item field in the table that has a button for adding/removing user trades
- [ ] Add event listener to the button of the modal that on click handles the objects for user data array. - [ ] Create div with data-view="my-trades" 
    - [ ] format of my trades div will be similar to the currency table. 
- [ ] pass the user data through the table creation to generate the table of user trades. 

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
